### PR TITLE
Feature/add document types

### PR DESCRIPTION
**Pull request by lukas-valenta**
## Description
Move document type detection from CLI here and add undefined to optional types.

## Motivation and Context

Document type detection is used in both CLI and SDK, so it makes sense to move it here.
`undefined` in optional types solves what seems to be a bug in typescript-is.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTION_GUIDE** document.
- [x] I haven't repeated the code. (DRY)
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by Jakub-Vacek** [comment]
Why did you decide to remove description from json schema?

**Comment by lukas-valenta** [comment]
> Why did you decide to remove description from json schema?

i did not, that's generated :shrug: i'll investigate

**Review by TheEdward162 — APPROVED** [review]
Seems ok on paper. Weird that the descriptions disappeared.

**Comment by lukas-valenta** [comment]
the descriptions are still there, they are just in the referenced object itself, probably because it was `ReferencedObject` and now is `ReferencedObject | undefined` and the description does not apply to `undefined` :shrug:

**Review by TheEdward162 — APPROVED** [review]

**Pull request merged**
